version: 2
jobs:
  build:
    working_directory: ~/standup
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Run npm install
          command: npm install
      - run:
          name: Install phantomjs
          command: "npm install phantomjs-prebuilt --save"
      - run:
          name: Run bower install
          command: "npm run bower -- install"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run npm test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
